# Generated by Django 5.1.2 on 2024-12-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_rename_nommbre_curso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
